package com.hylink.chexunjingwu.http.request

data class JqJqfkRequest(
    var jqlb: String? = null,
    var jqlbmc: String? = null,
    var jqlx: String? = null,
    var jqlxmc: String? = null,
    var jqxl: String? = null,
    var jqxlmc: String? = null,
    var ajfssj: String? = null,
    var ajjssj: String? = null,
    var cdccs: Int = 0,
    var fsdd: String? = null,
    var cdrs: Int = 0,
    var cjqk: String? = null,
    var bjrzjhm: String? = null,
    var fkrys //    "fkrys" :[{"mjjh":"030163"},{"mjjh":"030163"}]
    : List<Fkrys>? = null,
    var fscs //发生场所,
    : String? = null,
    var cjjg // 处警结果,
    : String? = null,
    var fscsmc //发生场所,
    : String? = null,
    var cjjgmc // 处警结果,
    : String? = null,
    var bjrxm: String? = null,
    var bjdh: String? = null,
    var cjdbh: String? = null,
    var jqbh: String? = null,
    var fkdwdm: String? = null,
    var mjdwmc: String? = null,
    var fkrbh: String? = null,
    var fkrxm: String? = null,
    var mjjh: String? = null,
    var zkimei: String? = null,
    var xzb: String? = null,
    var yzb: String? = null,
    var pic1: String? = null,
    var pic2: String? = null,
    var pic3: String? = null,
    var pic4: String? = null,
    var pic5: String? = null,
    var pic6: String? = null,
    var pic7: String? = null,
    var pic8: String? = null,
    var pic9: String? = null,
    var fk_police_alarm_flow_id: String? = null
) {
    data class Fkrys(var mjjh: String? = null, var mjxm: String? = null);
}